const KEY="ocarina-factory-v1";
let d=JSON.parse(localStorage.getItem(KEY)||"null")||{name:"",category:"",description:"",whatsapp:"",instagram:"",address:"",hours:"",hero:"",style:"calido",products:[]},step=0;
const themes={clasico:["Clásico","#252a27","#b48a5a"],comercial:["Comercial","#183f52","#d27c43"],calido:["Cálido","#6b4030","#b47743"],elegante:["Elegante","#171717","#9d835b"],profesional:["Profesional","#23463c","#73927e"]};
const esc=s=>String(s||"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]));
const wa=n=>{let x=(n||"").replace(/\D/g,"");if(x.length===10)x="549"+x;return x?"https://wa.me/"+x:"#"};
const ig=n=>{let x=(n||"").trim();return x?(x.indexOf("http")===0?x:"https://instagram.com/"+x.replace(/^@/,"")):"#"};
const save=()=>{localStorage.setItem(KEY,JSON.stringify(d));let s=document.querySelector(".save");if(s)s.textContent="Guardado automáticamente"};
const image=async(file,max)=>new Promise(res=>{if(!file)return res("");let r=new FileReader;r.onload=()=>{let im=new Image;im.onload=()=>{let sc=Math.min(1,max/im.width),c=document.createElement("canvas");c.width=im.width*sc;c.height=im.height*sc;c.getContext("2d").drawImage(im,0,0,c.width,c.height);res(c.toDataURL("image/jpeg",.82))};im.src=r.result};r.readAsDataURL(file)});
const field=(k,l,p)=>'<label class="field"><span>'+l+'</span><input data-f="'+k+'" value="'+esc(d[k])+'" placeholder="'+esc(p)+'"></label>';
const area=(k,l,p)=>'<label class="field"><span>'+l+'</span><textarea data-f="'+k+'" placeholder="'+esc(p)+'">'+esc(d[k])+'</textarea></label>';
function render(){let h='<div class="shell"><header class="top"><div class="brand">FÁBRICA OCARINA<small>Mini webs comerciales</small></div><div class="save">Borrador local</div></header><div class="layout"><section class="panel"><div class="steps>';
["Negocio","Catálogo","Diseño","Publicar"].forEach((x,i)=>h+='<button class="step '+(i===step?"active":"")+'" onclick="go('+i+')">'+(i+1)+'. '+x+'</button>');
h+='</div>';
h+='<div class="section '+(step===0?"active":"")+'"><div class="eyebrow">Paso 1</div><div class="title">Contame qué negocio vamos a mostrar.</div><p class="hint">Una ficha clara y profesional, pensada para compartir por WhatsApp.</p>'+field("name","Nombre del negocio","Ej.: Panadería María")+field("category","Rubro","Ej.: Panadería · Fotografía · Peluquería")+area("description","Descripción","Qué hace, qué ofrece y por qué deberían consultarle.")+'<div class="grid2">'+field("whatsapp","WhatsApp","Ej.: 299 123 4567")+field("instagram","Instagram","Ej.: @negocio")+'</div><div class="grid2">'+field("address","Dirección","Ej.: Calle 1, Chañar")+field("hours","Horarios","Ej.: Lun a sáb 9–13 y 17–21")+'</div><label class="field"><span>Foto principal</span><input type="file" id="heroFile" accept="image/*"></label><div class="actions"><button class="btn primary" onclick="go(1)">Continuar →</button></div></div>';
h+='<div class="section '+(step===1?"active":"")+'"><div class="eyebrow">Paso 2</div><div class="title">Qué vendés o qué servicio ofrecés.</div><p class="hint">No armamos una tienda complicada. Solo lo necesario para mostrar y pedir.</p>';
d.products.forEach((p,i)=>{h+='<div class="product"><div class="product-head"><b>Producto / servicio '+(i+1)+'</b><button class="remove" onclick="removeProduct('+i+')">Eliminar</button></div><label class="field"><span>Nombre</span><input value="'+esc(p.name)+'" oninput="up('+i+',\'name\',this.value)"></label><label class="field"><span>Descripción breve</span><input value="'+esc(p.description)+'" oninput="up('+i+',\'description\',this.value)"></label><div class="grid2"><label class="field"><span>Precio</span><input value="'+esc(p.price)+'" placeholder="Consultar" oninput="up('+i+',\'price\',this.value)"></label><label class="field"><span>Foto</span><input type="file" accept="image/*" onchange="pimg('+i+',this.files[0])"></label></div></div>'});
h+='<button class="btn secondary" onclick="addProduct()">＋ Agregar producto / servicio</button><div class="actions"><button class="btn secondary" onclick="go(0)">← Atrás</button><button class="btn primary" onclick="go(2)">Continuar →</button></div></div>';
h+='<div class="section '+(step===2?"active":"")+'"><div class="eyebrow">Paso 3</div><div class="title">Elegí un estilo. Nada más.</div><p class="hint">La fábrica se ocupa del diseño.</p><div class="style-grid>';
Object.keys(themes).forEach(k=>{let t=themes[k];h+='<button class="style-card '+(d.style===k?"selected":"")+'" onclick="d.style=\''+k+'\';save();render()"><b>'+t[0]+'</b><div class="swatches"><i class="swatch" style="background:'+t[1]+'"></i><i class="swatch" style="background:'+t[2]+'"></i></div></button>'});
h+='</div><div class="notice">Celular primero: foto, oferta, precio, pedido y contacto.</div><div class="actions"><button class="btn secondary" onclick="go(1)">← Atrás</button><button class="btn primary" onclick="go(3)">Vista final →</button></div></div>';
h+='<div class="section '+(step===3?"active":"")+'"><div class="eyebrow">Paso 4</div><div class="title">Lista para entregar.</div><p class="hint">Exportá una página HTML independiente, lista para subir a GitHub Pages.</p><button class="btn primary" style="width:100%" onclick="exportSite()">↓ Exportar mini-web</button><div class="notice">La publicación automática será la siguiente capa. Primero dejamos sólida la fábrica y el producto final.</div><div class="actions"><button class="btn secondary" onclick="go(2)">← Editar diseño</button></div></div>';
h+='</section><section class="preview"><div class="previewbar"><span>VISTA PREVIA REAL</span><span>'+esc(d.name||"Nuevo negocio")+'</span></div><div id="site" class="site"></div></section></div></div>';document.getElementById("app").innerHTML=h;bind();preview()}
function bind(){document.querySelectorAll("[data-f]").forEach(e=>e.oninput=()=>{d[e.dataset.f]=e.value;save();preview()});let f=document.getElementById("heroFile");if(f)f.onchange=async()=>{d.hero=await image(f.files[0],1400);save();render()}}
function preview(){let p=d.products.filter(x=>x.name),out='<section class="hero" style="background-image:url(\''+d.hero+'\')"><div class="hero-copy"><small>'+esc(d.category||"Negocio local")+'</small><h1>'+esc(d.name||"Tu negocio")+'</h1><p>'+esc(d.description||"Una descripción breve y clara de tu negocio.")+'</p></div></section><div class="body"><div class="links"><a class="link" href="'+wa(d.whatsapp)+'" target="_blank">WhatsApp</a>'+(d.instagram?'<a class="link alt" href="'+ig(d.instagram)+'" target="_blank">Instagram</a>':"")+'</div><h2>'+(p.length?"Productos y servicios":"Lo que ofrecemos")+'</h2><div class="products">';
if(p.length)p.forEach(x=>out+='<article class="prod">'+(x.image?'<img src="'+x.image+'" alt="">':"")+'<div><h3>'+esc(x.name)+'</h3><p>'+esc(x.description)+'</p><b>'+esc(x.price||"Consultar")+'</b><p><a class="order" href="'+wa(d.whatsapp)+'?text='+encodeURIComponent("Hola, vi tu página y quiero consultar por "+x.name)+'" target="_blank">PEDIR</a></p></div></article>');else out+='<div class="empty">Agregá productos o servicios en el paso 2.</div>';
out+='</div><div class="info"><div><b>Ubicación</b><br>'+esc(d.address||"A completar")+'</div><div><b>Horarios</b><br>'+esc(d.hours||"A completar")+'</div></div></div><div class="foot">Una mini-web creada con Fábrica Ocarina</div>';document.getElementById("site").innerHTML=out}
function go(n){step=n;render()} function addProduct(){d.products.push({name:"",description:"",price:"",image:""});save();render()} function removeProduct(i){d.products.splice(i,1);save();render()} function up(i,k,v){d.products[i][k]=v;save();preview()} async function pimg(i,f){d.products[i].image=await image(f,1000);save();render()}
function exportSite(){let html='<!doctype html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>'+esc(d.name||"Mini web")+'</title><style>body{margin:0;font-family:system-ui,sans-serif;background:#f7f4ee;color:#202522}.hero{min-height:52vh;background:#ddd center/cover;display:flex;align-items:end;padding:28px;color:#fff;position:relative}.hero:after{content:"";position:absolute;inset:0;background:linear-gradient(transparent,rgba(0,0,0,.7))}.copy{position:relative;z-index:1}.body{max-width:900px;margin:auto;padding:25px}.grid{display:grid;grid-template-columns:repeat(2,1fr);gap:14px}.card{background:#fff;border-radius:16px;overflow:hidden;border:1px solid #eee}.card img{width:100%;height:180px;object-fit:cover}.card div{padding:14px}.btn{display:inline-block;background:#202522;color:#fff;padding:11px 15px;border-radius:999px;margin:4px 4px 18px 0;text-decoration:none}@media(max-width:600px){.grid{grid-template-columns:1fr}}</style></head><body><section class="hero" style="background-image:url(\''+d.hero+'\')"><div class="copy"><small>'+esc(d.category)+'</small><h1>'+esc(d.name)+'</h1><p>'+esc(d.description)+'</p></div></section><div class="body"><a class="btn" href="'+wa(d.whatsapp)+'" target="_blank">WhatsApp</a>'+(d.instagram?'<a class="btn" href="'+ig(d.instagram)+'" target="_blank">Instagram</a>':"")+'<h2>Productos y servicios</h2><div class="grid">';
d.products.filter(x=>x.name).forEach(x=>html+='<article class="card">'+(x.image?'<img src="'+x.image+'" alt="">':"")+'<div><h3>'+esc(x.name)+'</h3><p>'+esc(x.description)+'</p><strong>'+esc(x.price||"Consultar")+'</strong><br><a class="btn" href="'+wa(d.whatsapp)+'?text='+encodeURIComponent("Hola, vi tu página y quiero consultar por "+x.name)+'" target="_blank">Pedir</a></div></article>');
html+='</div><h2>Información</h2><p><b>Dirección:</b> '+esc(d.address||"Consultar")+'</p><p><b>Horarios:</b><br>'+esc(d.hours||"Consultar")+'</p></div></body></html>';let b=new Blob([html],{type:"text/html"}),a=document.createElement("a");a.href=URL.createObjectURL(b);a.download=(d.name||"mini-web").toLowerCase().replace(/[^a-z0-9]+/g,"-")+".html";a.click()}
render();