const V2KEY="ocarina-factory-v2";
let V2=JSON.parse(localStorage.getItem(V2KEY)||"null")||{projects:[],active:null};
const V2RUBROS={Panadería:["Pan casero","Facturas","Torta"],Gastronomía:["Menú del día","Promo familiar","Postre"],Peluquería:["Corte","Color","Peinado"],Fotografía:["Sesión de fotos","Fotos de producto","Cobertura"],Artesanía:["Producto destacado","Personalizado","Regalo"],Productor:["Producto de temporada","Caja / combo","Pedido especial"],Profesor:["Clase individual","Clase grupal","Apoyo personalizado"],Servicios:["Servicio principal","Presupuesto","Servicio especial"],Tienda:["Producto destacado","Promoción","Pedido especial"]};
const v2save=()=>localStorage.setItem(V2KEY,JSON.stringify(V2));
const v2new=()=>({id:Date.now().toString(),name:"",category:"",description:"",whatsapp:"",instagram:"",address:"",hours:"",hero:"",style:"calido",products:[],updated:Date.now()});
const v2esc=s=>String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]));
const v2wa=n=>{let x=(n||"").replace(/\D/g,"");if(x.length===10)x="549"+x;return x?"https://wa.me/"+x:"#"};
function v2goHome(){V2.active=null;v2save();v2renderHome()}
function v2newProject(){const p=v2new();V2.projects.unshift(p);V2.active=p.id;v2save();v2renderEditor(0)}
function v2edit(id){V2.active=id;v2renderEditor(0)}
function v2dup(id){const p=V2.projects.find(x=>x.id===id),c=JSON.parse(JSON.stringify(p));c.id=Date.now().toString();c.name=(p.name||"Negocio")+" — copia";c.updated=Date.now();V2.projects.unshift(c);V2.active=c.id;v2save();v2renderEditor(0)}
function v2delete(){if(confirm("¿Eliminar este negocio?")){V2.projects=V2.projects.filter(x=>x.id!==V2.active);v2goHome()}}
function v2active(){return V2.projects.find(x=>x.id===V2.active)}
function v2set(k,v){const p=v2active();p[k]=v;p.updated=Date.now();v2save();v2preview()}
function v2add(){const p=v2active();p.products.push({name:"",description:"",price:"",image:""});v2save();v2renderEditor(1)}
function v2remove(i){v2active().products.splice(i,1);v2save();v2renderEditor(1)}
function v2suggest(){const p=v2active(),key=Object.keys(V2RUBROS).find(k=>(p.category||"").toLowerCase().includes(k.toLowerCase()))||"Servicios";p.products=V2RUBROS[key].map(n=>({name:n,description:"",price:"",image:""}));v2save();v2renderEditor(1)}
function v2step(n){V2.step=n;v2renderEditor(n)}
function v2homeCard(p){return '<article class="v2card"><div class="v2thumb" style="background-image:url(\''+p.hero+'\')"></div><div class="v2cardbody"><small>'+v2esc(p.category||"Negocio")+'</small><h2>'+v2esc(p.name||"Sin nombre")+'</h2><p>'+v2esc(p.description||"Sin descripción todavía.")+'</p><div class="v2actions"><button onclick="v2edit(\''+p.id+'\')">Abrir</button><button onclick="v2dup(\''+p.id+'\')">Duplicar</button></div></div></article>'}
function v2renderHome(){document.getElementById("app").innerHTML='<div class="v2shell"><header class="v2top"><div class="v2brand">FÁBRICA OCARINA<small>MINI WEBS COMERCIALES</small></div><button class="v2primary" onclick="v2newProject()">＋ NUEVO NEGOCIO</button></header><section class="v2hero"><div><span>PRODUCCIÓN REPETIBLE</span><h1>Una fábrica para hacer webs, no para programarlas.</h1><p>Cargás el negocio. La fábrica resuelve estructura, diseño, catálogo, WhatsApp y entrega.</p></div><div class="v2count"><b>'+V2.projects.length+'</b><small>negocios</small></div></section><section class="v2library">'+(V2.projects.length?V2.projects.map(v2homeCard).join(""):'<div class="v2empty"><b>Tu fábrica está lista.</b><p>Creá el primer negocio y después vas a poder duplicarlo, editarlo y producir otro sin empezar de cero.</p><button class="v2primary" onclick="v2newProject()">CREAR PRIMER NEGOCIO</button></div>')+'</section><div class="v2rule"><b>Regla:</b> el cliente ve una mini-web comercial. Vos ves una fábrica.</div></div>'}
function v2renderEditor(s){V2.step=s;const p=v2active();let body="";
if(s===0)body='<span class="v2eyebrow">01 · NEGOCIO</span><h1>La ficha maestra</h1><p class="v2hint">Estos datos alimentan toda la página.</p>'+v2field("name","Nombre del negocio","Ej.: Panadería María")+v2field("category","Rubro","Ej.: Panadería")+v2area("description","Descripción","Una presentación breve y clara.")+'<div class="v2grid">'+v2field("whatsapp","WhatsApp","299 123 4567")+v2field("instagram","Instagram","@negocio")+'</div><div class="v2grid">'+v2field("address","Dirección","San Patricio del Chañar")+v2field("hours","Horarios","Lun a sáb 9–13 / 17–21")+'</div><label class="v2field"><b>Foto principal</b><input type="file" accept="image/*" onchange="v2file(this)"></label><button class="v2secondary" onclick="v2suggest()">GENERAR OFERTA SUGERIDA</button><div class="v2next"><button class="v2primary" onclick="v2step(1)">CATÁLOGO →</button></div>';
if(s===1)body='<span class="v2eyebrow">02 · CATÁLOGO</span><h1>Lo que vendés</h1><p class="v2hint">La oferta debe poder entenderse y pedirse en pocos segundos.</p>'+p.products.map((x,i)=>'<div class="v2product"><b>OFERTA '+(i+1)+'</b><button onclick="v2remove('+i+')">Eliminar</button><input placeholder="Nombre" value="'+v2esc(x.name)+'" oninput="v2update('+i+',\'name\',this.value)"><input placeholder="Descripción" value="'+v2esc(x.description)+'" oninput="v2update('+i+',\'description\',this.value)"><div class="v2grid"><input placeholder="Precio / Consultar" value="'+v2esc(x.price)+'" oninput="v2update('+i+',\'price\',this.value)"><input type="file" accept="image/*" onchange="v2pfile('+i+',this)"></div></div>').join("")+'<button class="v2secondary" onclick="v2add()">＋ AGREGAR OFERTA</button><button class="v2secondary" onclick="v2suggest()">REGENERAR SUGERIDAS</button><div class="v2next"><button class="v2secondary" onclick="v2step(0)">← ATRÁS</button><button class="v2primary" onclick="v2step(2)">DISEÑO →</button></div>';
if(s===2)body='<span class="v2eyebrow">03 · DISEÑO</span><h1>Elegí una personalidad</h1><p class="v2hint">No diseñás. Elegís una dirección y la fábrica compone.</p><div class="v2styles">'+Object.entries({clasico:["Clásico","Ordenado"],comercial:["Comercial","Directo"],calido:["Cálido","Cercano"],elegante:["Elegante","Sobrio"],profesional:["Profesional","Confiable"]}).map(([k,x])=>'<button class="'+(p.style===k?"sel":"")+'" onclick="v2set(\'style\',\''+k+'\')"><b>'+x[0]+'</b><small>'+x[1]+'</small></button>').join("")+'</div><div class="v2note">La misma estructura sirve para panaderías, fotógrafos, peluquerías, productores, profesores y servicios.</div><div class="v2next"><button class="v2secondary" onclick="v2step(1)">← ATRÁS</button><button class="v2primary" onclick="v2step(3)">ENTREGA →</button></div>';
if(s===3)body='<span class="v2eyebrow">04 · ENTREGA</span><h1>Controlá y exportá</h1><p class="v2hint">La fábrica revisa lo esencial antes de crear la página final.</p><div class="v2checks"><div class="'+(p.name?"ok":"bad")+'">Nombre</div><div class="'+(p.whatsapp?"ok":"bad")+'">WhatsApp</div><div class="'+(p.hero?"ok":"bad")+'">Foto principal</div><div class="'+(p.products.length?"ok":"bad")+'">Oferta</div></div><button class="v2primary v2export" '+(p.name&&p.whatsapp?"":"disabled")+' onclick="v2export()">↓ EXPORTAR MINI-WEB</button><div class="v2note">La página exportada es independiente y compatible con GitHub Pages.</div><div class="v2next"><button class="v2secondary" onclick="v2step(2)">← DISEÑO</button></div>';
document.getElementById("app").innerHTML='<div class="v2shell"><header class="v2top"><div><button class="v2back" onclick="v2goHome()">← NEGOCIOS</button><div class="v2brand">FÁBRICA OCARINA<small>'+v2esc(p.name||"NUEVO NEGOCIO")+'</small></div></div><button class="v2danger" onclick="v2delete()">ELIMINAR</button></header><div class="v2editor"><section class="v2panel"><nav class="v2steps">'+["Negocio","Catálogo","Diseño","Entrega"].map((x,i)=>'<button class="'+(s===i?"on":"")+'" onclick="v2step('+i+')">'+(i+1)+" "+x+"</button>").join("")+'</nav>'+body+'</section><section class="v2preview"><div>VISTA PREVIA</div><div id="v2site"></div></section></div></div>';v2preview()}
function v2field(k,l,p){const x=v2active();return '<label class="v2field"><b>'+l+'</b><input value="'+v2esc(x[k])+'" placeholder="'+p+'" oninput="v2set(\''+k+'\',this.value)"></label>'}
function v2area(k,l,p){const x=v2active();return '<label class="v2field"><b>'+l+'</b><textarea placeholder="'+p+'" oninput="v2set(\''+k+'\',this.value)">'+v2esc(x[k])+'</textarea></label>'}
function v2update(i,k,v){v2active().products[i][k]=v;v2active().updated=Date.now();v2save();v2preview()}
async function v2read(file,max){return new Promise(res=>{if(!file)return res("");const r=new FileReader();r.onload=()=>{const im=new Image();im.onload=()=>{const sc=Math.min(1,max/im.width),c=document.createElement("canvas");c.width=im.width*sc;c.height=im.height*sc;c.getContext("2d").drawImage(im,0,0,c.width,c.height);res(c.toDataURL("image/jpeg",.82))};im.src=r.result};r.readAsDataURL(file)})}
async function v2file(input){const p=v2active();p.hero=await v2read(input.files[0],1400);v2save();v2renderEditor(V2.step)}
async function v2pfile(i,input){v2active().products[i].image=await v2read(input.files[0],1000);v2save();v2renderEditor(1)}
function v2preview(){const p=v2active(),offers=p.products.filter(x=>x.name),wa=v2wa(p.whatsapp);document.getElementById("v2site").innerHTML='<section class="v2sitehero" style="background-image:url(\''+p.hero+'\')"><div><small>'+v2esc(p.category||"NEGOCIO LOCAL")+'</small><h2>'+v2esc(p.name||"Tu negocio")+'</h2><p>'+v2esc(p.description||"Una presentación breve y clara.")+'</p></div></section><div class="v2sitebody"><a class="v2sitebtn" href="'+wa+'" target="_blank">WHATSAPP</a>'+(p.instagram?'<a class="v2sitebtn light" href="'+(p.instagram.startsWith("http")?p.instagram:"https://instagram.com/"+p.instagram.replace(/^@/,""))+'" target="_blank">INSTAGRAM</a>':"")+'<h3>Productos y servicios</h3><div class="v2offers">'+(offers.length?offers.map(x=>'<article>'+(x.image?'<img src="'+x.image+'">':"")+'<div><b>'+v2esc(x.name)+'</b><p>'+v2esc(x.description)+'</p><strong>'+v2esc(x.price||"Consultar")+'</strong><a href="'+wa+'?text='+encodeURIComponent("Hola, vi tu página y quiero consultar por "+x.name)+'" target="_blank">PEDIR</a></div></article>').join(""):'<div class="v2siteempty">Agregá una oferta para verla acá.</div>')+'</div><div class="v2siteinfo"><div><b>UBICACIÓN</b><br>'+v2esc(p.address||"A completar")+'</div><div><b>HORARIOS</b><br>'+v2esc(p.hours||"A completar")+'</div></div></div>'}
function v2export(){const p=v2active(),html='<!doctype html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>'+v2esc(p.name)+'</title><style>body{margin:0;font-family:system-ui,sans-serif;background:#f7f4ee;color:#202522}.hero{min-height:52vh;background:#ddd center/cover;display:flex;align-items:end;padding:28px;color:white;position:relative}.hero:after{content:"";position:absolute;inset:0;background:linear-gradient(transparent,rgba(0,0,0,.72))}.copy{position:relative;z-index:1}.body{max-width:920px;margin:auto;padding:25px}.btn{display:inline-block;background:#202522;color:#fff;padding:11px 15px;border-radius:999px;text-decoration:none;margin:4px 5px 20px 0;font-weight:800}.grid{display:grid;grid-template-columns:repeat(2,1fr);gap:14px}.card{background:white;border:1px solid #eee;border-radius:16px;overflow:hidden}.card img{width:100%;height:190px;object-fit:cover}.card div{padding:14px}@media(max-width:650px){.grid{grid-template-columns:1fr}}</style></head><body><section class="hero" style="background-image:url(\''+p.hero+'\')"><div class="copy"><small>'+v2esc(p.category)+'</small><h1>'+v2esc(p.name)+'</h1><p>'+v2esc(p.description)+'</p></div></section><main class="body"><a class="btn" href="'+v2wa(p.whatsapp)+'">WhatsApp</a><h2>Productos y servicios</h2><div class="grid">'+p.products.filter(x=>x.name).map(x=>'<article class="card">'+(x.image?'<img src="'+x.image+'">':"")+'<div><h3>'+v2esc(x.name)+'</h3><p>'+v2esc(x.description)+'</p><strong>'+v2esc(x.price||"Consultar")+'</strong><br><a class="btn" href="'+v2wa(p.whatsapp)+'?text='+encodeURIComponent("Hola, vi tu página y quiero consultar por "+x.name)+'">Pedir</a></div></article>').join("")+'</div><h2>Información</h2><p><b>Dirección:</b> '+v2esc(p.address||"Consultar")+'</p><p><b>Horarios:</b><br>'+v2esc(p.hours||"Consultar")+'</p></main></body></html>';const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([html],{type:"text/html"}));a.download=(p.name||"mini-web").toLowerCase().replace(/[^a-z0-9]+/g,"-")+".html";a.click()}
v2renderHome();